This Jupyter Notebook is part of the course [Python for Industry 4.0](https://www.udemy.com/course/python-for-industry-40/?referralCode=D7925A2D76BA4C94CA4E) from [Industry 4.0 Academy](https://www.i40a.com).

Latos© copyright 2022. All Rights Reserved.

# Numerical Computing Libraries - Class



## Numpy

### Numpy array and selecting data

In [ ]:
# import library
import numpy as np

In [ ]:
my_list = [1, 2, 3]

In [ ]:
# transform list into numpy array
my_array_1d = np.array(my_list)
my_array_1d

array([1, 2, 3])

In [ ]:
# create an array form 0 to 9 with step 1
x = np.arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# create an array from 0 to 9 with 10 evenly spaced numbers
x = np.linspace(0, 9, 10)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
my_array_2d = np.array(my_matrix)
my_array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# shape of the array
my_array_2d.shape

(3, 3)

In [ ]:
# select element in second row and third column
my_array_2d[1][2]

6

In [ ]:
my_array_2d[1, 2]

6

In [ ]:
my_array_2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [ ]:
# returns True for all values where the condition is true
ind = my_array_2d > 5
ind

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
# select only values where the condition is true
my_array_2d[ind]

array([6, 7, 8, 9])

In [ ]:
# select opposition from true
my_array_2d[~ind]

array([1, 2, 3, 4, 5])

In [ ]:
# replace all true by a given value
my_array_2d[ind] = 5
my_array_2d

array([[1, 2, 3],
       [4, 5, 5],
       [5, 5, 5]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# array with normal distributed random values
np.random.randn(3, 3)

array([[-1.24298386,  0.46550139,  1.238581  ],
       [ 0.52571835,  0.16374902,  0.07541738],
       [-0.94310784, -0.79735328,  0.48767692]])

In [ ]:
# array with uniform distributed random values
np.random.rand(3, 3)

array([[0.97482701, 0.40768465, 0.30173115],
       [0.71380032, 0.46380145, 0.12701674],
       [0.34973846, 0.52214612, 0.46813883]])

### Main operations


In [ ]:
# add the lists, i.e., concatenate lists
my_list + my_list

[1, 2, 3, 1, 2, 3]

In [ ]:
# add the arrays, the arithmetic operator will work element-wise
my_array_1d + my_array_1d

array([2, 4, 6])

In [ ]:
# same for multiplication and other operations
my_array_1d * my_array_1d

array([1, 4, 9])

In [ ]:
# arithmetic operation on the array with a scalar value
# opperation to each element
my_array_1d + 3

array([4, 5, 6])

In [ ]:
# same for multiplication and other operations
my_array_1d / 3

array([0.33333333, 0.66666667, 1.        ])

In [ ]:
# there are many functions built into Numpy
np.mean(my_array_2d)

5.0

In [ ]:
np.std(my_array_2d)

2.581988897471611

In [ ]:
# some methods too
my_array_2d.mean()

5.0

In [ ]:
my_array_2d.sum()

45

In [ ]:
my_array_2d.max()

9

In [ ]:
np.exp(my_array_2d)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [ ]:
np.sin(my_array_2d)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [ ]:
# for each column
np.mean(my_array_2d, axis=0) 

array([4., 5., 6.])

In [ ]:
# for each row
np.mean(my_array_2d, axis=1)

array([2., 5., 8.])

## Pandas


### Series and DataFrames

In [ ]:
import pandas as pd

In [ ]:
# Series from list - index is set automatically
records = [1, 2, 3, 4]
ser = pd.Series(records)
ser

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
# set index
index = ['a', 'b', 'c', 'd']
ser = pd.Series(records, index=index)
ser

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
# Series from dictionary
records_dic = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=records_dic)
ser

a    1
b    2
c    3
dtype: int64

In [ ]:
# DataFrame from dictionary
records_matrix = {'col1': [1, 2, 3], 'col2': [4, 5, 6]}
df = pd.DataFrame(data=records_matrix)
df

col1  col2
0     1     4
1     2     5
2     3     6

In [ ]:
# Dataframe from Numpy Array
# We will use a seed to generate an random array, this ensures we all have the same array
np.random.seed(123)
numpy_array = np.random.randn(4, 4)

df = pd.DataFrame(numpy_array, columns = ['col1', 'col2', 'col3', 'col4'], index=['a', 'b', 'c', 'd'])
df

col1      col2      col3      col4
a -1.085631  0.997345  0.282978 -1.506295
b -0.578600  1.651437 -2.426679 -0.428913
c  1.265936 -0.866740 -0.678886 -0.094709
d  1.491390 -0.638902 -0.443982 -0.434351

In [ ]:
# select values
df.values

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654, -2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  , -0.44398196, -0.43435128]])

In [ ]:
# select index
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
# select columns
df.columns

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

### Selecting data

More about selecting data: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html

In [ ]:
df

col1      col2      col3      col4
a -1.085631  0.997345  0.282978 -1.506295
b -0.578600  1.651437 -2.426679 -0.428913
c  1.265936 -0.866740 -0.678886 -0.094709
d  1.491390 -0.638902 -0.443982 -0.434351

In [ ]:
# select column with name 'col1'
df.col1

a   -1.085631
b   -0.578600
c    1.265936
d    1.491390
Name: col1, dtype: float64

In [ ]:
# alternative option
df['col1']

a   -1.085631
b   -0.578600
c    1.265936
d    1.491390
Name: col1, dtype: float64

In [ ]:
# select two columns by name
df[['col1', 'col2']]

col1      col2
a -1.085631  0.997345
b -0.578600  1.651437
c  1.265936 -0.866740
d  1.491390 -0.638902

In [ ]:
# select rows by position
df.iloc[:2]

col1      col2      col3      col4
a -1.085631  0.997345  0.282978 -1.506295
b -0.578600  1.651437 -2.426679 -0.428913

In [ ]:
df.iloc[[1, 3]]

col1      col2      col3      col4
b -0.57860  1.651437 -2.426679 -0.428913
d  1.49139 -0.638902 -0.443982 -0.434351

In [ ]:
# select rows and columns by position
df.iloc[:2, :2]

col1      col2
a -1.085631  0.997345
b -0.578600  1.651437

In [ ]:
# replace selected values
df.iloc[:2, :2] = 0
df

col1      col2      col3      col4
a  0.000000  0.000000  0.282978 -1.506295
b  0.000000  0.000000 -2.426679 -0.428913
c  1.265936 -0.866740 -0.678886 -0.094709
d  1.491390 -0.638902 -0.443982 -0.434351

In [ ]:
# find values based on condition
ind = df < 0
ind

col1   col2   col3  col4
a  False  False  False  True
b  False  False   True  True
c  False   True   True  True
d  False   True   True  True

In [ ]:
# replace values based on comparison
df[ind] = -1
df

col1  col2      col3  col4
a  0.000000   0.0  0.282978  -1.0
b  0.000000   0.0 -1.000000  -1.0
c  1.265936  -1.0 -1.000000  -1.0
d  1.491390  -1.0 -1.000000  -1.0

In [ ]:
# use more than one comparison
ind = (df > 0) & (df < 2)
df[ind] = 1
df

col1  col2  col3  col4
a   0.0   0.0   1.0  -1.0
b   0.0   0.0  -1.0  -1.0
c   1.0  -1.0  -1.0  -1.0
d   1.0  -1.0  -1.0  -1.0

In [ ]:
# oposite (not)
df[~ind] = 0
df

col1  col2  col3  col4
a   0.0   0.0   1.0   0.0
b   0.0   0.0   0.0   0.0
c   1.0   0.0   0.0   0.0
d   1.0   0.0   0.0   0.0

In [ ]:
# select data based on value
ind = df['col1'] == 0
ind 

a     True
b     True
c    False
d    False
Name: col1, dtype: bool

In [ ]:
# working with large dataset
numpy_array = np.random.randn(1000, 10)

df = pd.DataFrame(numpy_array)
df

0         1         2         3         4         5         6  \
0    2.205930  2.186786  1.004054  0.386186  0.737369  1.490732 -0.935834   
1    0.907105 -1.428681 -0.140069 -0.861755 -0.255619 -2.798589 -1.771533   
2    0.002846  0.688223 -0.879536  0.283627 -0.805367 -1.727669 -0.390900   
3    2.392365  0.412912  0.978736  2.238143 -1.294085 -1.038788  1.743712   
4    0.890706  1.754886  1.495644  1.069393 -0.772709  0.794863  0.314272   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.114699  0.745163 -0.635988  0.848133 -0.585542  0.086091 -0.101158   
996  1.397362 -1.419400  2.826198  0.793412  0.293470  0.652308  0.567850   
997 -1.350780 -0.112624  0.539086 -0.537706 -1.060740 -1.285079  1.071255   
998 -1.397932 -0.472266  0.581964  0.970613 -1.240970 -0.312947 -0.848947   
999 -0.490970 -1.081510  0.004801 -0.360797  0.012019  0.929787 -0.177048   

            7         8         9  
0    1.175829 -1.253881 -0.637752  
1   -0.699877  0.927462 -0.173636  
2    0.573806  0.338589 -0.011830  
3   -0.798063  0.029683  1.069316  
4   -1.326265  1.417299  0.807237  
..        ...       ...       ...  
995 -0.418401  0.490092  0.703430  
996  1.478910 -0.400071 -1.667558  
997  1.910933  0.649171 -0.597918  
998  2.377953  0.657501  0.213087  
999 -1.728908 -0.265183  0.712684  

[1000 rows x 10 columns]

In [ ]:
# return the first 5 rows.
df.head()

0         1         2         3
0  2.205930  2.186786  1.004054  0.386186
1  0.737369  1.490732 -0.935834  1.175829
2 -1.253881 -0.637752  0.907105 -1.428681
3 -0.140069 -0.861755 -0.255619 -2.798589
4 -1.771533 -0.699877  0.927462 -0.173636

In [ ]:
# return the last 5 rows.
df.tail()

0         1         2         3         4         5         6  \
995 -0.114699  0.745163 -0.635988  0.848133 -0.585542  0.086091 -0.101158   
996  1.397362 -1.419400  2.826198  0.793412  0.293470  0.652308  0.567850   
997 -1.350780 -0.112624  0.539086 -0.537706 -1.060740 -1.285079  1.071255   
998 -1.397932 -0.472266  0.581964  0.970613 -1.240970 -0.312947 -0.848947   
999 -0.490970 -1.081510  0.004801 -0.360797  0.012019  0.929787 -0.177048   

            7         8         9  
995 -0.418401  0.490092  0.703430  
996  1.478910 -0.400071 -1.667558  
997  1.910933  0.649171 -0.597918  
998  2.377953  0.657501  0.213087  
999 -1.728908 -0.265183  0.712684

### Loading data and basic data exploration
This database will be used frequently in our classes. The database we are using has been simplified from the original.

Original dataset: https://archive.ics.uci.edu/ml/datasets/Steel+Industry+Energy+Consumption+Dataset

more about Pandas IO: https://pandas.pydata.org/docs/user_guide/io.html

In [ ]:
path = 'https://raw.githubusercontent.com/i40a/datasets/main/steel_plant/mods/1/Steel_industry_data.csv' 
df = pd.read_csv(path, index_col='Date', parse_dates=True)

df.head()

Usage  LagRP  LeadRP  CO2     Day
Date                                                  
2018-01-01 00:15:00   3.17   2.95     0.0  0.0  Monday
2018-01-01 00:30:00   4.00   4.46     0.0  0.0  Monday
2018-01-01 00:45:00   3.24   3.28     0.0  0.0  Monday
2018-01-01 01:00:00   3.31   3.56     0.0  0.0  Monday
2018-01-01 01:15:00   3.82   4.50     0.0  0.0  Monday

In [ ]:
df.shape

(35040, 7)

In [ ]:
df['CO2'].head()

date
2018-01-01 00:15:00    0.0
2018-01-01 00:30:00    0.0
2018-01-01 00:45:00    0.0
2018-01-01 01:00:00    0.0
2018-01-01 01:15:00    0.0
Name: CO2, dtype: float64

In [ ]:
# check unique values in column
df['CO2'].unique()

array([0.  , 0.02, 0.03, 0.05, 0.06, 0.04, 0.01, 0.07])

In [ ]:
# count values in column
df['CO2'].value_counts()

0.00    20990
0.02     4643
0.03     4261
0.04     1834
0.01     1512
0.05     1363
0.06      410
0.07       27
Name: CO2, dtype: int64

In [ ]:
# pandas has many built in methods
df['CO2'].max()

0.07

In [ ]:
# basic statistics
df.describe()

Unnamed: 0         Usage         LagRP        LeadRP           CO2  \
count  35040.000000  35040.000000  35040.000000  35040.000000  35040.000000   
mean   17519.500000     27.386892     13.035384      3.870949      0.011524   
std    10115.321053     33.444380     16.306000      7.424463      0.016151   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%     8759.750000      3.200000      2.300000      0.000000      0.000000   
50%    17519.500000      4.570000      5.000000      0.000000      0.000000   
75%    26279.250000     51.237500     22.640000      2.090000      0.020000   
max    35039.000000    157.180000     96.910000     27.760000      0.070000   

              LagPF        LeadPF  
count  35040.000000  35040.000000  
mean      80.578056     84.367870  
std       18.921322     30.456535  
min        0.000000      0.000000  
25%       63.320000     99.700000  
50%       87.960000    100.000000  
75%       99.022500    100.000000  
max      100.000000    100.000000

In [ ]:
# pairwise correlation of columns
df.corr()

Usage     LagRP    LeadRP       CO2
Usage   1.000000  0.896150 -0.324922  0.988180
LagRP   0.896150  1.000000 -0.405142  0.886948
LeadRP -0.324922 -0.405142  1.000000 -0.332777
CO2     0.988180  0.886948 -0.332777  1.000000

In [ ]:
# create new column based on operation
df['Usage (MWh)'] = df['Usage'] / 1000
df.head()

Usage  LagRP  LeadRP  CO2     Day  Usage (MWh)
Date                                                               
2018-01-01 00:15:00   3.17   2.95     0.0  0.0  Monday      0.00317
2018-01-01 00:30:00   4.00   4.46     0.0  0.0  Monday      0.00400
2018-01-01 00:45:00   3.24   3.28     0.0  0.0  Monday      0.00324
2018-01-01 01:00:00   3.31   3.56     0.0  0.0  Monday      0.00331
2018-01-01 01:15:00   3.82   4.50     0.0  0.0  Monday      0.00382

In [ ]:
# select only rows based in condition
index_keep = df['CO2'] > 0
df_clean = df[index_keep]
df_clean.shape

(14050, 6)

In [ ]:
# save back to csv
df_clean.to_csv('clean_data.csv')

### Working with time series

In [ ]:
df.index

DatetimeIndex(['2018-01-01 00:15:00', '2018-01-01 00:30:00',
               '2018-01-01 00:45:00', '2018-01-01 01:00:00',
               '2018-01-01 01:15:00', '2018-01-01 01:30:00',
               '2018-01-01 01:45:00', '2018-01-01 02:00:00',
               '2018-01-01 02:15:00', '2018-01-01 02:30:00',
               ...
               '2018-12-31 21:45:00', '2018-12-31 22:00:00',
               '2018-12-31 22:15:00', '2018-12-31 22:30:00',
               '2018-12-31 22:45:00', '2018-12-31 23:00:00',
               '2018-12-31 23:15:00', '2018-12-31 23:30:00',
               '2018-12-31 23:45:00', '2019-01-01 00:00:00'],
              dtype='datetime64[ns]', name='date', length=35040, freq=None)

In [ ]:
import datetime as dt # library to work with datetime

# select based on start date
start = dt.datetime(2018, 2, 1)

ind = df.index > start
df[ind].head()

Usage  LagRP  LeadRP   CO2       Day  Usage (MWh)
Date                                                                  
2018-02-01 00:15:00  84.49  42.48     0.0  0.04  Thursday      0.08449
2018-02-01 00:30:00  77.22  42.23     0.0  0.04  Thursday      0.07722
2018-02-01 00:45:00  74.05  38.99     0.0  0.03  Thursday      0.07405
2018-02-01 01:00:00  88.96  46.04     0.0  0.04  Thursday      0.08896
2018-02-01 01:15:00  76.64  41.54     0.0  0.04  Thursday      0.07664

In [ ]:
# resample with daily mean
df.resample("1d").mean().head()

Usage      LagRP    LeadRP       CO2  Usage (MWh)
Date                                                             
2018-01-01   3.667789   1.717474  9.989053  0.000000     0.003668
2018-01-02  41.137917  16.446667  3.063125  0.000000     0.041138
2018-01-03  37.094687  13.388542  2.766562  0.015938     0.037095
2018-01-04  51.850521  21.443438  2.339271  0.022604     0.051851
2018-01-05  48.790625  20.428542  2.689167  0.021250     0.048791

In [ ]:
# resampling with monthly sum 
df.resample("M").sum()

Usage     LagRP    LeadRP    CO2  Usage (MWh)
Date                                                         
2018-01-31  126178.28  54426.49  11675.81  53.96    126.17828
2018-02-28   91552.06  35922.42  11723.70  39.27     91.55206
2018-03-31   80233.00  32020.50  12761.92  33.64     80.23300
2018-04-30   78769.37  34737.68  12091.03  33.35     78.76937
2018-05-31   79059.53  38430.20  12764.51  33.51     79.05953
2018-06-30   65404.60  32895.12  12388.10  27.10     65.40460
2018-07-31   81674.49  39674.85   9867.89  35.02     81.67449
2018-08-31   68559.32  38203.50  11109.77  28.44     68.55932
2018-09-30   57883.28  33196.77   9617.35  23.92     57.88328
2018-10-31   84664.54  49595.46   7430.39  35.81     84.66454
2018-11-30   86217.50  42863.48   8357.57  36.52     86.21750
2018-12-31   59437.07  24790.35  15849.93  23.27     59.43707
2019-01-31       3.67      3.02      0.07   0.00      0.00367

In [ ]:
# rolling window
# moving average in one hour window
df_ma = df.rolling('1h').mean()
df_ma.head()

Usage     LagRP  LeadRP  CO2  Usage (MWh)
Date                                                           
2018-01-01 00:15:00  3.1700  2.950000     0.0  0.0     0.003170
2018-01-01 00:30:00  3.5850  3.705000     0.0  0.0     0.003585
2018-01-01 00:45:00  3.4700  3.563333     0.0  0.0     0.003470
2018-01-01 01:00:00  3.4300  3.562500     0.0  0.0     0.003430
2018-01-01 01:15:00  3.5925  3.950000     0.0  0.0     0.003593

In [ ]:
import plotly.graph_objects as go

# Create traces
fig = go.Figure()
fig.add_trace(go.Scatter(x=df['Usage'].index, y=df['Usage'].values, mode='lines', name='Raw', line_shape='hv'))
fig.add_trace(go.Scatter(x=df_ma['Usage'].index, y=df_ma['Usage'].values, mode='lines', name='Moving Average', line_shape='hv'))

fig.show()

### Working with missing data

More details: https://pandas.pydata.org/docs/user_guide/missing_data.html

In [ ]:
df_short = df.iloc[:10]
df_short

Usage  LagRP  LeadRP  CO2     Day  Usage (MWh)
Date                                                               
2018-01-01 00:15:00   3.17   2.95     0.0  0.0  Monday      0.00317
2018-01-01 00:30:00   4.00   4.46     0.0  0.0  Monday      0.00400
2018-01-01 00:45:00   3.24   3.28     0.0  0.0  Monday      0.00324
2018-01-01 01:00:00   3.31   3.56     0.0  0.0  Monday      0.00331
2018-01-01 01:15:00   3.82   4.50     0.0  0.0  Monday      0.00382
2018-01-01 01:30:00   3.28   3.56     0.0  0.0  Monday      0.00328
2018-01-01 01:45:00   3.60   4.14     0.0  0.0  Monday      0.00360
2018-01-01 02:00:00   3.60   4.28     0.0  0.0  Monday      0.00360
2018-01-01 02:15:00   3.28   3.64     0.0  0.0  Monday      0.00328
2018-01-01 02:30:00   3.78   4.72     0.0  0.0  Monday      0.00378

In [ ]:
df_short = df_short.resample('10min').mean()
df_short

Usage  LagRP  LeadRP  CO2  Usage (MWh)
Date                                                       
2018-01-01 00:10:00   3.17   2.95     0.0  0.0      0.00317
2018-01-01 00:20:00    NaN    NaN     NaN  NaN          NaN
2018-01-01 00:30:00   4.00   4.46     0.0  0.0      0.00400
2018-01-01 00:40:00   3.24   3.28     0.0  0.0      0.00324
2018-01-01 00:50:00    NaN    NaN     NaN  NaN          NaN
2018-01-01 01:00:00   3.31   3.56     0.0  0.0      0.00331
2018-01-01 01:10:00   3.82   4.50     0.0  0.0      0.00382
2018-01-01 01:20:00    NaN    NaN     NaN  NaN          NaN
2018-01-01 01:30:00   3.28   3.56     0.0  0.0      0.00328
2018-01-01 01:40:00   3.60   4.14     0.0  0.0      0.00360
2018-01-01 01:50:00    NaN    NaN     NaN  NaN          NaN
2018-01-01 02:00:00   3.60   4.28     0.0  0.0      0.00360
2018-01-01 02:10:00   3.28   3.64     0.0  0.0      0.00328
2018-01-01 02:20:00    NaN    NaN     NaN  NaN          NaN
2018-01-01 02:30:00   3.78   4.72     0.0  0.0      0.00378

In [ ]:
# drop rows with nan values
df_short.dropna()

Unnamed: 0  Usage  LagRP  LeadRP  CO2  LagPF  LeadPF  \
date                                                                        
2018-01-01 00:10:00         0.0   3.17   2.95     0.0  0.0  73.21   100.0   
2018-01-01 00:30:00         1.0   4.00   4.46     0.0  0.0  66.77   100.0   
2018-01-01 00:40:00         2.0   3.24   3.28     0.0  0.0  70.28   100.0   
2018-01-01 01:00:00         3.0   3.31   3.56     0.0  0.0  68.09   100.0   
2018-01-01 01:10:00         4.0   3.82   4.50     0.0  0.0  64.72   100.0   
2018-01-01 01:30:00         5.0   3.28   3.56     0.0  0.0  67.76   100.0   
2018-01-01 01:40:00         6.0   3.60   4.14     0.0  0.0  65.62   100.0   
2018-01-01 02:00:00         7.0   3.60   4.28     0.0  0.0  64.37   100.0   
2018-01-01 02:10:00         8.0   3.28   3.64     0.0  0.0  66.94   100.0   
2018-01-01 02:30:00         9.0   3.78   4.72     0.0  0.0  62.51   100.0   

                     Usage (MWh)  
date                              
2018-01-01 00:10:00      0.00317  
2018-01-01 00:30:00      0.00400  
2018-01-01 00:40:00      0.00324  
2018-01-01 01:00:00      0.00331  
2018-01-01 01:10:00      0.00382  
2018-01-01 01:30:00      0.00328  
2018-01-01 01:40:00      0.00360  
2018-01-01 02:00:00      0.00360  
2018-01-01 02:10:00      0.00328  
2018-01-01 02:30:00      0.00378

In [ ]:
# fill nan by given value
df_short.fillna(value=0)

Usage  LagRP  LeadRP  CO2  Usage (MWh)
Date                                                       
2018-01-01 00:10:00   3.17   2.95     0.0  0.0      0.00317
2018-01-01 00:20:00   0.00   0.00     0.0  0.0      0.00000
2018-01-01 00:30:00   4.00   4.46     0.0  0.0      0.00400
2018-01-01 00:40:00   3.24   3.28     0.0  0.0      0.00324
2018-01-01 00:50:00   0.00   0.00     0.0  0.0      0.00000
2018-01-01 01:00:00   3.31   3.56     0.0  0.0      0.00331
2018-01-01 01:10:00   3.82   4.50     0.0  0.0      0.00382
2018-01-01 01:20:00   0.00   0.00     0.0  0.0      0.00000
2018-01-01 01:30:00   3.28   3.56     0.0  0.0      0.00328
2018-01-01 01:40:00   3.60   4.14     0.0  0.0      0.00360
2018-01-01 01:50:00   0.00   0.00     0.0  0.0      0.00000
2018-01-01 02:00:00   3.60   4.28     0.0  0.0      0.00360
2018-01-01 02:10:00   3.28   3.64     0.0  0.0      0.00328
2018-01-01 02:20:00   0.00   0.00     0.0  0.0      0.00000
2018-01-01 02:30:00   3.78   4.72     0.0  0.0      0.00378

In [ ]:
# replace nan by last value
df_short.fillna(method='pad')

Usage  LagRP  LeadRP  CO2  Usage (MWh)
Date                                                       
2018-01-01 00:10:00   3.17   2.95     0.0  0.0      0.00317
2018-01-01 00:20:00   3.17   2.95     0.0  0.0      0.00317
2018-01-01 00:30:00   4.00   4.46     0.0  0.0      0.00400
2018-01-01 00:40:00   3.24   3.28     0.0  0.0      0.00324
2018-01-01 00:50:00   3.24   3.28     0.0  0.0      0.00324
2018-01-01 01:00:00   3.31   3.56     0.0  0.0      0.00331
2018-01-01 01:10:00   3.82   4.50     0.0  0.0      0.00382
2018-01-01 01:20:00   3.82   4.50     0.0  0.0      0.00382
2018-01-01 01:30:00   3.28   3.56     0.0  0.0      0.00328
2018-01-01 01:40:00   3.60   4.14     0.0  0.0      0.00360
2018-01-01 01:50:00   3.60   4.14     0.0  0.0      0.00360
2018-01-01 02:00:00   3.60   4.28     0.0  0.0      0.00360
2018-01-01 02:10:00   3.28   3.64     0.0  0.0      0.00328
2018-01-01 02:20:00   3.28   3.64     0.0  0.0      0.00328
2018-01-01 02:30:00   3.78   4.72     0.0  0.0      0.00378

In [ ]:
# replace nan by interpolated value
df_short.interpolate()

Usage  LagRP  LeadRP  CO2  Usage (MWh)
Date                                                       
2018-01-01 00:10:00  3.170  2.950     0.0  0.0     0.003170
2018-01-01 00:20:00  3.585  3.705     0.0  0.0     0.003585
2018-01-01 00:30:00  4.000  4.460     0.0  0.0     0.004000
2018-01-01 00:40:00  3.240  3.280     0.0  0.0     0.003240
2018-01-01 00:50:00  3.275  3.420     0.0  0.0     0.003275
2018-01-01 01:00:00  3.310  3.560     0.0  0.0     0.003310
2018-01-01 01:10:00  3.820  4.500     0.0  0.0     0.003820
2018-01-01 01:20:00  3.550  4.030     0.0  0.0     0.003550
2018-01-01 01:30:00  3.280  3.560     0.0  0.0     0.003280
2018-01-01 01:40:00  3.600  4.140     0.0  0.0     0.003600
2018-01-01 01:50:00  3.600  4.210     0.0  0.0     0.003600
2018-01-01 02:00:00  3.600  4.280     0.0  0.0     0.003600
2018-01-01 02:10:00  3.280  3.640     0.0  0.0     0.003280
2018-01-01 02:20:00  3.530  4.180     0.0  0.0     0.003530
2018-01-01 02:30:00  3.780  4.720     0.0  0.0     0.003780