This Jupyter Notebook is part of the course [Python for Industry 4.0](https://www.udemy.com/course/python-for-industry-40/?referralCode=D7925A2D76BA4C94CA4E) from [Industry 4.0 Academy](https://www.i40a.com).

Latos© copyright 2022. All Rights Reserved.

# Numerical Computing Libraries - Exercises


## Numpy

Create a Numpy 4 x 4 array of random integers between 0 and 19 (Google it!)

In [ ]:
import numpy as np
matrix = np.random.randint(0, 20, (4, 4))
matrix

array([[ 0, 14,  4,  9],
       [ 1,  3,  1,  8],
       [ 5,  9, 16,  0],
       [ 9,  4, 18,  1]])

Divide all values by 2

In [ ]:
matrix = matrix / 2
matrix

array([[0. , 7. , 2. , 4.5],
       [0.5, 1.5, 0.5, 4. ],
       [2.5, 4.5, 8. , 0. ],
       [4.5, 2. , 9. , 0.5]])

Select values greater than 5

In [ ]:
ind = matrix > 5
selected = matrix[ind]
selected

array([7., 8., 9.])

Evaluate the mean for the remaining values

In [ ]:
np.mean(selected)

8.0

Create a Numpy 3 x 2 array of zero values (Google it!)

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## Pandas

Create a Pandas Series with 10 rows using a numpy array of random numbers

In [ ]:
import pandas as pd

array = np.random.randn(10)
ser = pd.Series(array)
ser

0    0.760252
1    0.803347
2   -0.634495
3   -1.605476
4   -0.825159
5    0.034048
6    0.141855
7   -0.370635
8    0.893171
9    0.285200
dtype: float64

Create a Pandas DataFrame with a 100x100 numpy matrix of random normal distrubuted values

In [ ]:
matrix = np.random.randn(100, 100)
df = pd.DataFrame(matrix)
df

0         1         2         3         4         5         6   \
0  -0.856659 -0.652530 -0.094409  1.223176 -0.263724 -0.762128 -0.570061   
1   2.363798 -0.161346 -0.766344  0.047888  1.924299  1.420050 -0.232210   
2  -1.928763  0.693860 -1.114424  0.743903  0.375140 -1.493951  0.125184   
3  -1.061461 -1.413789 -0.135311 -0.741437  1.345053  0.331731  0.414988   
4   0.198201  0.442709 -0.352897 -0.437935  1.210216 -0.336766  0.141314   
..       ...       ...       ...       ...       ...       ...       ...   
95 -2.495368  1.058020 -1.657066  1.907412 -0.188015 -0.211097  0.003525   
96  0.194254 -0.867498  0.552809  1.152524 -0.515533  1.205732 -0.078385   
97 -1.604354  0.411011  0.579075 -0.172675 -1.671721 -2.292072 -0.171875   
98  0.582329  0.277870  0.392910 -1.004956  0.939007  0.282266  0.037585   
99  0.019897  0.870427 -0.898160  0.760264  0.825105  1.230397 -1.037681   

          7         8         9   ...        90        91        92        93  \
0   0.450365  0.085823  1.622214  ... -1.989683  0.493990  1.439624 -0.095680   
1   0.565097 -0.187798 -0.398102  ...  0.765904  0.225306  0.755984  1.223919   
2   2.278124  0.347606 -0.794004  ... -0.755781  2.781985 -0.005310  1.704175   
3  -0.383361 -0.169152  1.305868  ... -0.696738 -0.450830  0.737209 -2.657036   
4  -0.757330  0.441220 -0.105061  ...  1.610912  0.964205  0.632723 -0.097864   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95 -0.599483 -1.345240 -0.148530  ...  2.261197  1.299680 -0.772048  0.043601   
96 -0.178465  0.197148 -0.899586  ...  0.215850  0.659767  1.084247  0.967379   
97  1.242957 -0.088191  1.267536  ...  0.241387  0.573626  0.326147  1.971794   
98  0.218357  0.115857 -0.555159  ... -1.069644  0.179273  0.438190  1.394612   
99 -1.504911 -0.586798  0.824327  ...  1.551260 -0.320604  1.127042  0.192958   

          94        95        96        97        98        99  
0  -0.592489 -1.493894 -0.153311 -0.558559  0.639968 -0.458279  
1   1.288624 -0.336128 -1.055473 -1.060063 -2.036594 -1.477515  
2   0.330511  0.561578  0.301857 -1.137953 -1.160622  2.393538  
3  -0.236881  0.966719  1.089060  0.459327 -0.705026 -0.757854  
4  -0.902307  0.112622  1.256491  0.268543 -0.697906 -1.481404  
..       ...       ...       ...       ...       ...       ...  
95 -1.348496 -0.514731 -0.110109  0.674195  0.784608  0.501941  
96  1.989946 -1.346579 -0.862787  0.965098  1.528967  1.421202  
97  0.018441  0.210011 -0.861701 -0.038031 -0.915489 -0.848548  
98 -0.409784 -0.767944 -0.652436  0.513968  1.526816  1.191348  
99 -1.918267  0.485684 -0.987952  0.276182 -1.150763 -0.253115  

[100 rows x 100 columns]

Evaluate de standard deviation of each row

In [ ]:
df.std()

0     0.924939
1     0.995751
2     0.844943
3     0.871938
4     1.023067
        ...   
95    1.025190
96    0.904306
97    1.069420
98    0.965507
99    0.951561
Length: 100, dtype: float64

Find the basic statistics of the DataFrame
(mean must be close to zero and standard deviation close to 1)

In [ ]:
df.describe()

0           1           2           3           4           5   \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.008766    0.025900    0.122766    0.083374    0.026114   -0.016932   
std      0.924939    0.995751    0.844943    0.871938    1.023067    1.014945   
min     -2.495368   -3.045281   -2.049581   -2.443615   -2.169348   -2.292072   
25%     -0.546337   -0.540441   -0.442469   -0.445365   -0.741716   -0.749199   
50%      0.061873    0.112434    0.223520    0.119200    0.020866   -0.167833   
75%      0.575359    0.679433    0.691336    0.721076    0.725119    0.676277   
max      2.363798    2.366897    1.956615    1.907412    2.365584    2.535883   

               6           7           8           9   ...          90  \
count  100.000000  100.000000  100.000000  100.000000  ...  100.000000   
mean     0.078227    0.139705    0.014255   -0.060233  ...   -0.030338   
std      1.040509    0.961858    0.888520    0.972380  ...    1.109502   
min     -2.786862   -2.691800   -2.080892   -2.579728  ...   -2.932723   
25%     -0.575519   -0.547522   -0.499099   -0.690318  ...   -0.841603   
50%      0.086361    0.207040    0.062383   -0.105822  ...    0.081132   
75%      0.741838    0.778123    0.659991    0.627375  ...    0.797968   
max      2.136304    2.777102    2.244439    2.039013  ...    2.321529   

               91          92          93          94          95          96  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.012645    0.176588    0.137434   -0.090206    0.007285   -0.011751   
std      0.892377    0.931545    1.064823    1.014980    1.025190    0.904306   
min     -2.179458   -1.756481   -2.657036   -2.413567   -2.018483   -1.998432   
25%     -0.555058   -0.539709   -0.747353   -0.786316   -0.605193   -0.653112   
50%      0.000861    0.046682    0.203263   -0.195432    0.011352   -0.127746   
75%      0.576807    0.860328    1.003429    0.575733    0.550391    0.724863   
max      2.781985    3.094172    2.226372    2.276720    3.281435    2.233144   

               97          98          99  
count  100.000000  100.000000  100.000000  
mean     0.032123    0.071609    0.122727  
std      1.069420    0.965507    0.951561  
min     -3.262703   -2.529641   -1.937656  
25%     -0.824760   -0.449988   -0.475213  
50%      0.070325    0.025113    0.186604  
75%      0.677260    0.668163    0.709214  
max      3.528356    2.997141    2.713857  

[8 rows x 100 columns]

## Manufacturing

### Repeat exercises with libraries

Repeat the total weekly production in chapter 2 using Numpy. It is not necessary to build a Python function.

In [ ]:
production_week = np.array([230, 254, 214, 208, 235, 120])

mean = production_week.mean()
total_week = production_week.sum()
print(total_week, mean)

1261 210.16666666666666


Repeat the alarm detection example in chapter 2 using Pandas series as input.

Tip: double clicks to reveal!
<!---
Use logical operations to find the index of values greater than alarm_limite and check if number of trues is higher than 0 (sum(ind) > 0)
-->


In [ ]:
def trigger_alarm(sensor_data, alarm_limite):
    ind = sensor_data > alarm_limite
    if sum(ind) > 0:
        return 'Alarm!'
    else:
        return 'Normal'

In [ ]:
# test the function for the following inputs
sensor_trigger = pd.Series([1.2, 3, 4.1, 2.2])
alarm_limite = 4

trigger_alarm(sensor_trigger, alarm_limite)

'Alarm!'

In [ ]:
# test again for the following inputs
sensor_dont_trigger = pd.Series([1.2, 3, 3.1, 2.2])
trigger_alarm(sensor_dont_trigger, alarm_limite)

'Normal'

### Basic exercises with the steel plant dataset

Load the csv file in the path below:

In [ ]:
path = 'https://raw.githubusercontent.com/i40a/datasets/main/steel_plant/mods/1/Steel_industry_data.csv' 
df = pd.read_csv(path, index_col='Date', parse_dates=True)

df.head()

Usage  LagRP  LeadRP  CO2     Day
Date                                                  
2018-01-01 00:15:00   3.17   2.95     0.0  0.0  Monday
2018-01-01 00:30:00   4.00   4.46     0.0  0.0  Monday
2018-01-01 00:45:00   3.24   3.28     0.0  0.0  Monday
2018-01-01 01:00:00   3.31   3.56     0.0  0.0  Monday
2018-01-01 01:15:00   3.82   4.50     0.0  0.0  Monday

Use the trigger_alarm function to check if Usage column has values greater than 140

In [ ]:
trigger_alarm(df['Usage'], 140)

'Alarm!'

Let's consider that values greater than 140  for Usage are outliers. Revome them from the DataFrame

In [ ]:
ind = df['Usage'] > 140
df_clean = df[~ind]
df_clean.head()

Usage  LagRP  LeadRP  CO2     Day
Date                                                  
2018-01-01 00:15:00   3.17   2.95     0.0  0.0  Monday
2018-01-01 00:30:00   4.00   4.46     0.0  0.0  Monday
2018-01-01 00:45:00   3.24   3.28     0.0  0.0  Monday
2018-01-01 01:00:00   3.31   3.56     0.0  0.0  Monday
2018-01-01 01:15:00   3.82   4.50     0.0  0.0  Monday

Use the trigger_alarm function again, now for the data without outlier

In [ ]:
trigger_alarm(df_clean['Usage'], 140)

'Normal'

Now consider that when usage is greater than 80 plant is in full production. What is the ratio of time in total production / total time? Consider sampling time as constant.

Tip:

<!---
Find the index of values greater than 80. Sum the number of trues (sum(ind)) and divide by the total of rows in the DataFrame.
-->




In [ ]:
threshold = 80
ind = df['Usage'] > threshold
sum(ind) / len(df)

0.09466324200913243

### Filter by date

Build a function that receives a start and end date and filters a DataFrame based on this time range.

In [ ]:
def filter_by_date(df, start, end):
    ind = (df.index > start) & (df.index < end)
    return df[ind]

Filter the steel plant dataset for February data only.

In [ ]:
import datetime as dt
start = dt.datetime(2018, 2, 1)
end = dt.datetime(2018, 3, 1)

filter_by_date(df, start, end)

Usage  LagRP  LeadRP   CO2        Day
Date                                                      
2018-02-01 00:15:00  84.49  42.48     0.0  0.04   Thursday
2018-02-01 00:30:00  77.22  42.23     0.0  0.04   Thursday
2018-02-01 00:45:00  74.05  38.99     0.0  0.03   Thursday
2018-02-01 01:00:00  88.96  46.04     0.0  0.04   Thursday
2018-02-01 01:15:00  76.64  41.54     0.0  0.04   Thursday
...                    ...    ...     ...   ...        ...
2018-02-28 22:45:00   5.36   6.19     0.0  0.00  Wednesday
2018-02-28 23:00:00   5.33   6.26     0.0  0.00  Wednesday
2018-02-28 23:15:00   5.33   5.83     0.0  0.00  Wednesday
2018-02-28 23:30:00   5.29   5.76     0.0  0.00  Wednesday
2018-02-28 23:45:00   5.29   5.58     0.0  0.00  Wednesday

[2687 rows x 5 columns]

### Data compression algorithm (hard)

Code a compression algorithm that reads a Pandas Series and keeps the values only if the difference between the value and the last saved value is greater than a certain threshold.

Tip:
<!---
1. The first value is always saved, so start a Series called "compressed" with only the first value.
2. Iterate over all indexes using the for loop (for index in ser.index).
3. If the difference between the value of this index and the last saved value is greater than the threshold, save (compressed[index] = value).
4. The difference can be positive or negative, so repeat the if statement or use abs(value - compressed[-1]) to ignore the negative sign in the first statement.
-->


In [ ]:
def compress(ser, threshold):
    compressed = ser[[0]]

    for index in ser.index:
        value = ser[index]
        if abs(value - compressed[-1]) > threshold:
            compressed[index] = value

    return compressed

Run the function to df['Usage'] and threshold = 7. Save the results in a variable named "compressed".

In [ ]:
ser = df['Usage']
threshold = 7

compressed = compress(ser, threshold)
compressed.head()

Date
2018-01-01 00:15:00     3.17
2018-01-02 08:15:00    29.02
2018-01-02 08:30:00    46.19
2018-01-02 09:00:00    56.20
2018-01-02 09:45:00    48.13
Name: Usage, dtype: float64

Evaluate the compression ratio (uncompressed size / compressed size)

In [ ]:
len(df) / len(compressed) 

4.011907487978017

Resample the original dataset to 1 hour sampling time using mean method. Save the result in a variable named "df_resampled".

In [ ]:
df_resampled = df.resample("1h").mean()

Evaluate the compression ratio for the resampled data.

In [ ]:
len(df) / len(df_resampled)

3.9995434311151694

The compression ratio for both compression and resampling are very close (close to 4).


The following code show the original, compressed, and resampled data. 

Can you see any difference in the general pattern of the line after the compression? Do you think resampling or compression kept best the pattern of the original data?

In [ ]:
import plotly.graph_objects as go

# Create traces
fig = go.Figure()
fig.add_trace(go.Scatter(x=df['Usage'].index, y=df['Usage'].values, mode='lines', name='Raw', line_shape='hv'))
fig.add_trace(go.Scatter(x=compressed.index, y=compressed.values, mode='lines', name='Compressed', line_shape='hv'))
fig.add_trace(go.Scatter(x=df_resampled['Usage'].index, y=df_resampled['Usage'].values, mode='lines', name='Resampled', line_shape='hv'))

fig.show()